= Spring Multimodule Sandbox

This project shows how to use Spring in a multi-module setting.

*Features*

* Spring Boot
* Spring Functional Bean Definition Dsl
* Gradle Kotlin Dsl. We shorten that to kradle though.

The project imagines you want to produce pizza. For that you need a *catalogue* of all possible ingredients and a *factory* with an inventory that can make pizzas. The structure follows the ideas from the link:http://c4model.com/[C4 Model].

* Containers are things that are running, spring containers in our case. Named after italian cities, naturally.
* Components are collections of classes, that have the same overall purpose.

== Usage

* Build complete project `./gradlew build`
* Run individual project `./gradlew :container:rome:bootRun`
* Test only medium tests `./gradlew mediumTest`
* List available tasks `./gradlew tasks`

== Gradle

Gradle built system has two major building blocks

1. project
2. task

A Gradle build system is made up of one or more projects and each project contains one or more tasks. A project in Gradle is an abstract concept that represents an artifact that needs to be built.

=== Wrapper

Please make sure you have the newest Gradle (>v6) version installed if you run the `gradle wrapper` task.

=== BuildSrc

BuildSrc is a project in the root of your build. Everything written there will be shared by all your build scripts. We can use buildSrc to write our own gradle tasks, plugins or extensions functions that will be available in all `build.gradle.kts`.

=== Test

The link:https://docs.gradle.org/current/userguide/java_testing.html[JavaTesting Guide] and the official docs for the link:https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html[Test Api].

=== Gradle Kotlin Dsl

* You can find lots of official link:https://github.com/gradle/kotlin-dsl-samples/tree/master/samples[Gradle Kotlin Dsl Samples] online
* The official docs provide a link:https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/[Migration Guide] from Groovy to Kotlin
* There is also the link:https://docs.gradle.org/current/userguide/kotlin_dsl.html[Gradle Kotlin DSL User Guide] to consider.

== Spring

=== Spring Kotlin Bean DSL

The Spring Kotlin Bean DSL was introduced with Spring 5. An excellent resource if you want to migrate to the new dsl is link:https://blog.frankel.ch/spring-boot-migrating-functional/[Spring Boot, migrating to functional].

link:https://spring.io/blog/2019/01/21/manual-bean-definitions-in-spring-boot[Manual AutoConfiguration Defintions] are a thing in Spring.

=== Spring Fu

link:https://github.com/rodolphocouto/spring-fu-sample/[other sample].

=== Spring Router DSL

link:https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#router-dsl[Spring Router DSL].

=== Kotlin Script Templates

link:https://github.com/sdeleuze/kotlin-script-templating[sample project] and link:https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#kotlin-script-templates[reference docs].

=== Spring Testing

link:https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-test-auto-configuration.html[Test Auto-configuration Annotations].