= Spring Multimodule Sandbox

This project shows how to use Spring in a multi-module setting.

*Features*

* Spring Boot
* Spring Functional Bean Definition Dsl
* Gradle Kotlin Dsl. We shorten that to kradle though.

The project imagines you want to produce pizza. For that you need a *catalogue* of all possible ingredients and a *factory* with an inventory that can make pizzas. The structure follows the ideas from the link:http://c4model.com/[C4 Model].

* Containers are things that are running, spring containers in our case. Named after italian cities, naturally.
* Components are collections of classes, that have the same overall purpose.

== Usage

* Build complete project `./gradlew build`
* Run individual project `./gradlew :container:rome:bootRun`
* Test only medium tests `./gradlew mediumTest`
* List available tasks `./gradlew tasks`

== Gradle

The link:https://gradle.org/[Gradle] build tool is an alternative to link:https://maven.apache.org/[Maven]. It's built system consists of two major building blocks

1. project
2. task

A Gradle build system is made up of one or more projects and each project contains one or more tasks. A project represents an artifact that needs to be built.

Gradle has a simple link:https://docs.gradle.org/current/userguide/command_line_interface.html[command-line interface].

* View all projects `./gradlew projects`
* View the available tasks `./gradlew tasks`

=== Wrapper

Please make sure you have the newest Gradle (>v6) version installed if you run the `gradle wrapper` task.

=== BuildSrc

BuildSrc is a project in the root of your build. Everything written there will be shared by all your build scripts. We can use buildSrc to write our own gradle tasks, plugins or extensions functions that will be available in all `build.gradle.kts`. The gradle team also recommends placing dependency versions there.

BuildSrc Plugins can be applied the same way as regular plugins. We can specify an id alias by placing a properties file in `buildSrc/src/main/resources/META-INF.gradle-plugins`.

=== Test

Specifying test and test options is relatively straightforward using gradle. The link:https://docs.gradle.org/current/userguide/java_testing.html[JavaTesting Guide] and the official docs for the link:https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html[Test Api] provide a good starting point. They also help when it comes to defining a more complicated test setup using multiple testsets.

In our case we wrote a custom buildSrc plugin to define multiple testsets that can share code between them. We could have also used the link:https://github.com/unbroken-dome/gradle-testsets-plugin[Gradle TestSets plugin], an example code base can be found link:https://github.com/Richargh/testsets-plugin-krdl-kt-sandbox[here].

=== Gradle Kotlin Dsl

* You can find lots of official link:https://github.com/gradle/kotlin-dsl-samples/tree/master/samples[Gradle Kotlin Dsl Samples] online
* The official docs provide a link:https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/[Migration Guide] from Groovy to Kotlin
* There is also the link:https://docs.gradle.org/current/userguide/kotlin_dsl.html[Gradle Kotlin DSL User Guide] to consider.

=== Plugins

Plugins can modify your build quite a lot. For example they can add tasks or new extensions to a project. They are usually added in the `plugins {}` block of a `build.gradle.kts`. The normal way is to supply an `id("...")`.

If you want an executable jar, you would usually add the application plugin `plugins { id("org.gradle.application") }`. Gradle provides aliases for the common plugin they supply. So `id("org.gradle.application")` becomes `\`application\``. JetBrains provides a different alias for all the kotlin plugins and `id("org.jetbrains.kotlin.jvm")` becomes `kotlin("jvm")`.

== Spring

=== Spring Kotlin Bean DSL

The Spring Kotlin Bean DSL was introduced with Spring 5. An excellent resource if you want to migrate from component scan to the new dsl is link:https://blog.frankel.ch/spring-boot-migrating-functional/[Spring Boot, migrating to functional].

=== Spring Router DSL

link:https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#router-dsl[Spring Router DSL].

=== Configuring Spring

link:https://spring.io/blog/2019/01/21/manual-bean-definitions-in-spring-boot[Manual AutoConfiguration Defintions] are a thing in Spring.

==== Spring Fu

link:https://github.com/rodolphocouto/spring-fu-sample/[other sample].

=== Spring Testing

link:https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-test-auto-configuration.html[Test Auto-configuration Annotations].

=== Kotlin Script Templates

link:https://github.com/sdeleuze/kotlin-script-templating[sample project] and link:https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#kotlin-script-templates[reference docs].
